---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup,message = FALSE,include=FALSE}
library(flexdashboard)
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() %>% 
  drop_na()
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
grade_boro = nyc_inspections %>% 
  mutate(grade = recode(grade,  
                              "A" = " Grade A ",
                              "B" = " Grade B",
                              "C" = " Grade C",
                              "Z" = " Grade Pending",
                              "P" = " Grade Pending Issued on re-opening",
                              "N"  = "Not Yet Graded")) 


grade_boro %>% 
  count(grade, boro) %>% 
  mutate(grade = fct_reorder(grade, n)) %>% 
  plot_ly( x = ~ boro ,y = ~n, color= ~grade, type = "bar") %>% 
    layout(title = "Inspection Grades by Borough",
         xaxis = list(title = "Borough"), 
         yaxis = list(title = "Count of Inspection Grade"))
    
   
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
inspection_scores_boro = nyc_inspections %>% 
  mutate(score = as.numeric(score)) %>% 
    select(boro, score ) %>% 
  group_by(boro) 

nyc_inspections %>% 
  mutate(boro = fct_reorder(boro, score))%>%
  plot_ly(x = ~boro, y = ~score, color = ~boro, type = "box", colors = "viridis") %>% 
  layout(title = "Inspection Scores by Borough",
         xaxis = list(title = "Borough"), 
         yaxis = list(title = "Inspection Score"))

```

### Chart C

```{r}

inspections_over_time = nyc_inspections %>% 
   mutate(score = as.numeric(score)) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>%
  select(year,score, month ) %>% 
  filter(year == "2023") %>%
  group_by(month) %>% 
  summarise(avg_score = mean(score, na.rm = TRUE))


scatter_ggplot = 
  inspections_over_time %>% 
ggplot(aes(x = month, y = avg_score, group = 1))+
  geom_point(color = "black", alpha = 1) +
  geom_line(color = "purple") +
  labs(title = "Average Inspection Scores Across all of NYC by Month in 2023"
       , x = "Month",
       y = "Average Score") +
  theme_minimal()
 

ggplotly(scatter_ggplot)



```

